In [1]:
import pandas as pd
import numpy as np

seed = 1234

In [2]:
df = pd.read_csv('MSCallGraph_sampled.csv')

In [3]:
df

,um,rpctype,dm
0,94dce029795f9357501c763b763bf951c8290ad1744ec1...,mc,76dd56a9f2e9c563a1cf719314e2ba5257bd2eb99a623d...
1,5c17bb2b4e1bfb38ccbe6cffde6c49b854800d62a80343...,db,e887321342cfcab81228e67f8fcf836e45313dc45b1811...
2,1db622d2ef805ba3c30f129fc21afb8cf145109380bffe...,rpc,fd4d92f4328a8714b7100aa132bfc4d40271b5120113ea...
3,fd4d92f4328a8714b7100aa132bfc4d40271b5120113ea...,db,e3b1ec3da44f91aad3e564d2291d723b6afb4d5ac7ccb4...
4,9f14b8cd62aa14111695d8d170020805e508ca2168604a...,mc,7b3d2d6c8a8760081d2124b7a3fa1f795661105c79593c...
...,...,...,...
41379,c20e26ec49d020ebe2b44aa6e3119993049eff078ff576...,db,8cce245e0d489e9ecf271400b101b92be1d371fe7895e5...
41380,59b1463de2fbe73df7cdba3fb71cde40e2bfddb9efec55...,db,bf88d94e7daa4eaf9401ff71ba09616ec59b990ba38861...
41381,12bc3fe2791d9f2946a74114ff349795461e695a099ae3...,mq,5aefad73e20ae83cd0bf473107dd290e74f9a8b12aa6bc...
41382,150f30cbcef004e2e3964d5327c7cb25e3f1dea47199dc...,db,4346785c51657ac12c3b03236666aec286c40f6eafafd1...
41383,a97b125d84a970b6461797b4106db49a6ba587416af9c5...,mq,13e763803f427787c427876463cf189a7f3c8e4182b0e0...

In [4]:
entities = set(df['dm']) | set(df['um'])
len(entities)

16657

In [5]:
baseline = []
for entity in entities:
    baseline.append(df[df['dm'] == entity].head(1))
    baseline.append(df[df['um'] == entity].head(1))

In [6]:
baseline_df = pd.concat(baseline)
baseline_df = baseline_df.drop_duplicates()
baseline_df

,um,rpctype,dm
3803,b5a35565229f602efb3cead95ad21c907c92331d91eab1...,mc,f891bd43fa457a0e1e76d38cf6467d1c977168361ddb23...
14535,33454e6e00fb545de80ba684f1e0701cef4a09467c939a...,db,b674014c47fff2a5fe9f251ddc500e1bec77653f451d82...
9240,da5ac969e69381adca65851753b9ed2decfe4509420484...,mq,c7cabb47eb0f49e2910c8b5502c5f92273d176fbfeef7c...
9241,c7cabb47eb0f49e2910c8b5502c5f92273d176fbfeef7c...,db,4297298c6473159054aae055a89427adf3d3908a529883...
15999,87f3522e7b259f45398e495f02e0afd54d9bd8f77959c6...,db,a9a073cfaee8605951c8e9ea0d9f873f88c22741991f48...
...,...,...,...
6686,a5cb4c5ddf4a5658ac6128fe5b256579d2fdb22d295846...,db,82c26f7019be1c60aaddd0b2659767e7faa0a66cb02b3a...
1075,69bce5bcddf088304c4fc692b6fbbe0a15417dee93a8af...,db,3b3d16904cc36473f919ee2be3853c905eb00f8984df3d...
7164,d6d9fc487215c50426045c51ecd64ddb8f940aff4a4c28...,mc,6fdc57f9ef0df26c02f7a0285f1efb11554c6a91f2e483...
1865,2acfd7708f39b85b3a441f9e804b269630cb72c115c8ac...,mq,9c2e1e0e2e9a71881cbbf95fab38cc978feee0ba1e7fed...
17422,35114acfb54c54fb9618f23cd28bbc57c765f597df1409...,db,17547efc1acf968eb4b85ef4835a6cf31df231d0b5eca2...

In [7]:
n_train_items = int(len(df)*0.64)
n_items_to_add = n_train_items - len(baseline_df)
print("the number of items to add to the train set is: ",n_items_to_add)

the number of items to add to the train set is:  8730

In [8]:
not_baseline_df = df.merge(baseline_df, how='outer', indicator=True).loc[lambda x : x['_merge']=='left_only'].drop('_merge',axis= 1)
not_baseline_df

,um,rpctype,dm
724,5c17bb2b4e1bfb38ccbe6cffde6c49b854800d62a80343...,mc,c964e78e1ee643babee3c48807207a39596bdc816e5ceb...
1060,d2c895bd5c7de55f381310fd1b94ce9d518bf4ac22e22f...,mq,c133d5f7eb91a127d94757ce7915ee3bceba0a25e95146...
1327,bbff5552531b3f6d4c8f4ea4c66dc3b991f504e0612c2c...,rpc,c87dbc550c2a943d3e44472303561950225211665e1d07...
1413,24601dd8b36f856eb0a4d759866f475bc62cf843ffe092...,rpc,cf5f15ad4585ff713e95993380824a1f0fc1d85792f8dd...
1441,1cf15b5b8ce80d005ceb2d77ef34a226b178dc27fc3d93...,mc,84a652246581e7ac111e7d84bc1d632a88b880ea5dbe70...
...,...,...,...
41379,c20e26ec49d020ebe2b44aa6e3119993049eff078ff576...,db,8cce245e0d489e9ecf271400b101b92be1d371fe7895e5...
41380,59b1463de2fbe73df7cdba3fb71cde40e2bfddb9efec55...,db,bf88d94e7daa4eaf9401ff71ba09616ec59b990ba38861...
41381,12bc3fe2791d9f2946a74114ff349795461e695a099ae3...,mq,5aefad73e20ae83cd0bf473107dd290e74f9a8b12aa6bc...
41382,150f30cbcef004e2e3964d5327c7cb25e3f1dea47199dc...,db,4346785c51657ac12c3b03236666aec286c40f6eafafd1...
41383,a97b125d84a970b6461797b4106db49a6ba587416af9c5...,mq,13e763803f427787c427876463cf189a7f3c8e4182b0e0...

In [9]:
not_baseline_train = not_baseline_df.sample(n_items_to_add,random_state = seed)
train_df = pd.concat([baseline_df, not_baseline_train])
train_df

,um,rpctype,dm
3803,b5a35565229f602efb3cead95ad21c907c92331d91eab1...,mc,f891bd43fa457a0e1e76d38cf6467d1c977168361ddb23...
14535,33454e6e00fb545de80ba684f1e0701cef4a09467c939a...,db,b674014c47fff2a5fe9f251ddc500e1bec77653f451d82...
9240,da5ac969e69381adca65851753b9ed2decfe4509420484...,mq,c7cabb47eb0f49e2910c8b5502c5f92273d176fbfeef7c...
9241,c7cabb47eb0f49e2910c8b5502c5f92273d176fbfeef7c...,db,4297298c6473159054aae055a89427adf3d3908a529883...
15999,87f3522e7b259f45398e495f02e0afd54d9bd8f77959c6...,db,a9a073cfaee8605951c8e9ea0d9f873f88c22741991f48...
...,...,...,...
22911,4f1bff38f31da15de0b1dd0854f27c4a1555494a704b4c...,db,ded742ee83d2e3ac6b4952f7dcad22041aed0fd1bbc5d8...
38336,40bef09fcce3e5fa238c0f1d43243d56af38ec44c8d0f8...,rpc,d755fbe29a37be86b4334f6ad7c8c2c6486377f970da4d...
32469,2778cbf888500779361a677eacef7afffb05d7d3f9b983...,db,e28d45c18486e8b489d6cef73dfdc87881f91670d3e296...
34501,c2b8e526bf09520b26d0982daa6954712e829d3c6cfe18...,rpc,8382f8ca896075af917acb020ce8c7dc322a09d8e8a734...
35799,b654ed6ca503c46bec57a80930f193602c1d7997eb8c7e...,rpc,71154d296a76f16d25b11d130f4458e39992276efb0b5b...

In [10]:
remaining_df = not_baseline_df.drop(not_baseline_train.index)

In [11]:
validation_df = remaining_df
validation_df

,um,rpctype,dm
724,5c17bb2b4e1bfb38ccbe6cffde6c49b854800d62a80343...,mc,c964e78e1ee643babee3c48807207a39596bdc816e5ceb...
1060,d2c895bd5c7de55f381310fd1b94ce9d518bf4ac22e22f...,mq,c133d5f7eb91a127d94757ce7915ee3bceba0a25e95146...
1327,bbff5552531b3f6d4c8f4ea4c66dc3b991f504e0612c2c...,rpc,c87dbc550c2a943d3e44472303561950225211665e1d07...
1413,24601dd8b36f856eb0a4d759866f475bc62cf843ffe092...,rpc,cf5f15ad4585ff713e95993380824a1f0fc1d85792f8dd...
1742,6f83eed1237572824fa0807fb2414de831c989c6392cca...,rpc,6f83eed1237572824fa0807fb2414de831c989c6392cca...
...,...,...,...
41376,ac06c2122ac45a80afb95e30fb2c0c73b96042efe4e6e3...,db,d975e4765706ce3b7a3f424ab5b848d206b5b8a7fa9bf0...
41377,dcd12288c7943871c82626398763fc1b08dce250000117...,mq,04770eb280a2990bec7939304582f07a57a5d5fe710009...
41378,5d887bdb9fd24cea365fb7ce018526df1d39b11630081b...,db,9d44d9b1700bbe79bc626669c2b036ed2d69c4fb59ba34...
41379,c20e26ec49d020ebe2b44aa6e3119993049eff078ff576...,db,8cce245e0d489e9ecf271400b101b92be1d371fe7895e5...
41383,a97b125d84a970b6461797b4106db49a6ba587416af9c5...,mq,13e763803f427787c427876463cf189a7f3c8e4182b0e0...

Transductive checks

In [12]:
train_entities = set(train_df['dm']) or set(train_df['um'])
valid_entities = set(validation_df['dm']) or set(validation_df['um'])

In [13]:
assert(valid_entities.issubset(train_entities))

In [14]:
train_relations = set(train_df['rpctype'])
valid_relations = set(validation_df['rpctype'])

In [15]:
assert(valid_relations.issubset(train_relations))

Check to see if there is test leakage

In [16]:
assert(0==len(pd.merge(train_df, validation_df)))

In [17]:
def create_triplets(df):
    triplets = []
    for i in range(len(df)):
        head = df.iloc[i]['dm']
        tail = df.iloc[i]['um']
        rel = df.iloc[i]['rpctype']
        triplets.append([head,rel,tail])
    return triplets

In [18]:
import asposecells
import jpype
jpype.startJVM()

from asposecells.api import Workbook, FileFormatType

def create_tsv(triplets, file_name):


    # Create Workbook object.
    workbook = Workbook(FileFormatType.TSV)

    # Access the first worksheet of the workbook.
    worksheet = workbook.getWorksheets().get(0)

    # Get the desired cell(s) of the worksheet and input the value into the cell(s).


    i = 1
    for elem in triplets: 
        worksheet.getCells().get("A"+str(i)).putValue(elem[0])
        worksheet.getCells().get("B"+str(i)).putValue(elem[1])
        worksheet.getCells().get("C"+str(i)).putValue(elem[2])
        i+=1


    # Save the workbook as TSV file.
    workbook.save(file_name)


    file = open(file_name,'r')  
    lines = file.readlines()  
    file.close()
    file = open(file_name,'w')  
    lines = lines[:-1]
    file.writelines(lines)
    file.close()

In [20]:
datasets = [train_df, validation_df]
names = ["train", "validation"]

In [21]:
for elem in zip(datasets,names):
    create_tsv(create_triplets(elem[0]),f"MSCallGraph_{elem[1]}_transductive_sampled.tsv")
jpype.shutdownJVM()