In [1]:
import pandas as pd
import numpy as np

seed = 1234

In [2]:
df = pd.read_csv('MSCallGraph_sampled.csv')

In [3]:
df

,um,rpctype,dm
0,94dce029795f9357501c763b763bf951c8290ad1744ec1...,mc,76dd56a9f2e9c563a1cf719314e2ba5257bd2eb99a623d...
1,5c17bb2b4e1bfb38ccbe6cffde6c49b854800d62a80343...,db,e887321342cfcab81228e67f8fcf836e45313dc45b1811...
2,1db622d2ef805ba3c30f129fc21afb8cf145109380bffe...,rpc,fd4d92f4328a8714b7100aa132bfc4d40271b5120113ea...
3,fd4d92f4328a8714b7100aa132bfc4d40271b5120113ea...,db,e3b1ec3da44f91aad3e564d2291d723b6afb4d5ac7ccb4...
4,9f14b8cd62aa14111695d8d170020805e508ca2168604a...,mc,7b3d2d6c8a8760081d2124b7a3fa1f795661105c79593c...
...,...,...,...
41379,c20e26ec49d020ebe2b44aa6e3119993049eff078ff576...,db,8cce245e0d489e9ecf271400b101b92be1d371fe7895e5...
41380,59b1463de2fbe73df7cdba3fb71cde40e2bfddb9efec55...,db,bf88d94e7daa4eaf9401ff71ba09616ec59b990ba38861...
41381,12bc3fe2791d9f2946a74114ff349795461e695a099ae3...,mq,5aefad73e20ae83cd0bf473107dd290e74f9a8b12aa6bc...
41382,150f30cbcef004e2e3964d5327c7cb25e3f1dea47199dc...,db,4346785c51657ac12c3b03236666aec286c40f6eafafd1...
41383,a97b125d84a970b6461797b4106db49a6ba587416af9c5...,mq,13e763803f427787c427876463cf189a7f3c8e4182b0e0...

In [4]:
entities = set(df['dm']) | set(df['um'])
len(entities)

16657

In [5]:
baseline = []
for entity in entities:
    baseline.append(df[df['dm'] == entity].head(1))
    baseline.append(df[df['um'] == entity].head(1))

In [6]:
baseline_df = pd.concat(baseline)
baseline_df = baseline_df.drop_duplicates()
baseline_df

,um,rpctype,dm
12588,ac06c2122ac45a80afb95e30fb2c0c73b96042efe4e6e3...,db,640291d6ec22e108543fab8f59ceeeb1046e26b4794dae...
14029,a00af0e171813da5e8109aba202d0e9c7d58a27c14ce83...,rpc,39b4c8fbcd94df8fb90c0f37d4866d5c5b13b294c4b964...
14030,39b4c8fbcd94df8fb90c0f37d4866d5c5b13b294c4b964...,rpc,de93367b32ae1873de4c22a944ed1c95cc7d8e082d1ae0...
7553,40ffc05267de09b1b99d51f5630097d4006548d60a5de0...,mq,939a83d9ea703f34e6c86876b50f2ffc94e81fad4c25ff...
18611,f5286217c28fbee5c9c084087e2ffbfbba4808bbdd8001...,db,fbc3610dc494a80821fad4b90f8b96f93a2a17d0d1b2dc...
...,...,...,...
11855,1444f9468ec8c5761e5090225b1c87e46e8e6f1145329d...,db,56b94cee93d66e51620b7a95b4500008d083ea5957bc1f...
18620,36fd84f1aae82d8aabe12f4c85da743e99dc0cd42b2527...,db,95ccebf2254b255022656dadd56bc5ac10c282550fe4a9...
3323,4ab265f54516248ee8873be7d6441912456ce17e84f399...,mc,055ed8d225329c2fac39e0a3e4e641445380c0800a23dd...
10622,6b3de38ce727d7a097829c79b86ae6446afe984f9f45d5...,mq,0519cba332510a8795f29de77e612d56bde3e32ddcd8f3...
10623,0519cba332510a8795f29de77e612d56bde3e32ddcd8f3...,rpc,45d3b0167914f5ed51226176dea46c30939461486dfb51...

In [7]:
n_train_items = int(len(df)*0.64)
n_items_to_add = n_train_items - len(baseline_df)
print("the number of items to add to the train set is: ",n_items_to_add)

the number of items to add to the train set is:  8730

In [8]:
not_baseline_df = df.merge(baseline_df, how='outer', indicator=True).loc[lambda x : x['_merge']=='left_only'].drop('_merge',axis= 1)
not_baseline_df

,um,rpctype,dm
724,5c17bb2b4e1bfb38ccbe6cffde6c49b854800d62a80343...,mc,c964e78e1ee643babee3c48807207a39596bdc816e5ceb...
1060,d2c895bd5c7de55f381310fd1b94ce9d518bf4ac22e22f...,mq,c133d5f7eb91a127d94757ce7915ee3bceba0a25e95146...
1327,bbff5552531b3f6d4c8f4ea4c66dc3b991f504e0612c2c...,rpc,c87dbc550c2a943d3e44472303561950225211665e1d07...
1413,24601dd8b36f856eb0a4d759866f475bc62cf843ffe092...,rpc,cf5f15ad4585ff713e95993380824a1f0fc1d85792f8dd...
1441,1cf15b5b8ce80d005ceb2d77ef34a226b178dc27fc3d93...,mc,84a652246581e7ac111e7d84bc1d632a88b880ea5dbe70...
...,...,...,...
41379,c20e26ec49d020ebe2b44aa6e3119993049eff078ff576...,db,8cce245e0d489e9ecf271400b101b92be1d371fe7895e5...
41380,59b1463de2fbe73df7cdba3fb71cde40e2bfddb9efec55...,db,bf88d94e7daa4eaf9401ff71ba09616ec59b990ba38861...
41381,12bc3fe2791d9f2946a74114ff349795461e695a099ae3...,mq,5aefad73e20ae83cd0bf473107dd290e74f9a8b12aa6bc...
41382,150f30cbcef004e2e3964d5327c7cb25e3f1dea47199dc...,db,4346785c51657ac12c3b03236666aec286c40f6eafafd1...
41383,a97b125d84a970b6461797b4106db49a6ba587416af9c5...,mq,13e763803f427787c427876463cf189a7f3c8e4182b0e0...

In [9]:
not_baseline_train = not_baseline_df.sample(n_items_to_add,random_state = seed)
train_df = pd.concat([baseline_df, not_baseline_train])
train_df

,um,rpctype,dm
12588,ac06c2122ac45a80afb95e30fb2c0c73b96042efe4e6e3...,db,640291d6ec22e108543fab8f59ceeeb1046e26b4794dae...
14029,a00af0e171813da5e8109aba202d0e9c7d58a27c14ce83...,rpc,39b4c8fbcd94df8fb90c0f37d4866d5c5b13b294c4b964...
14030,39b4c8fbcd94df8fb90c0f37d4866d5c5b13b294c4b964...,rpc,de93367b32ae1873de4c22a944ed1c95cc7d8e082d1ae0...
7553,40ffc05267de09b1b99d51f5630097d4006548d60a5de0...,mq,939a83d9ea703f34e6c86876b50f2ffc94e81fad4c25ff...
18611,f5286217c28fbee5c9c084087e2ffbfbba4808bbdd8001...,db,fbc3610dc494a80821fad4b90f8b96f93a2a17d0d1b2dc...
...,...,...,...
22911,4f1bff38f31da15de0b1dd0854f27c4a1555494a704b4c...,db,ded742ee83d2e3ac6b4952f7dcad22041aed0fd1bbc5d8...
38336,40bef09fcce3e5fa238c0f1d43243d56af38ec44c8d0f8...,rpc,d755fbe29a37be86b4334f6ad7c8c2c6486377f970da4d...
32469,2778cbf888500779361a677eacef7afffb05d7d3f9b983...,db,e28d45c18486e8b489d6cef73dfdc87881f91670d3e296...
34501,c2b8e526bf09520b26d0982daa6954712e829d3c6cfe18...,rpc,8382f8ca896075af917acb020ce8c7dc322a09d8e8a734...
35799,b654ed6ca503c46bec57a80930f193602c1d7997eb8c7e...,rpc,71154d296a76f16d25b11d130f4458e39992276efb0b5b...

In [10]:
remaining_df = not_baseline_df.drop(not_baseline_train.index)

In [11]:
validation_df = remaining_df.sample(frac = 0.44, random_state = seed)
validation_df

,um,rpctype,dm
31430,fb750d9e38225fe305f254bb00cfba22138845328abf15...,db,0b690009c89d596ad4a7d983a5c566481a7ca2a9d6e58c...
28366,a25db459a097f3b6aa173c3ed5dcd8377f2d342c591d6b...,mc,6fca8fa37b692ca3b475513e7948bd10db3a6cc0e32391...
20018,7b3b9cb2faed94c69ae18e8275ec186a4ffe6b2e258878...,mc,f138108ba795397cdee8f700c77322b1318f8026c3f4d3...
23588,48e8faba4a168f803d7f16abb37ff877edd589b8081166...,db,95900100f9e20bf81687d900091a06d732fd660ea3520a...
25425,672b13877ae01745ec085064409ad377150789569f5c84...,rpc,90c357ca77801f0d38c1f4cffa2e3d51ef7b1fca91ae35...
...,...,...,...
20354,804eb0d44ed9f1ade6bdb61113d3390ae28b226eeab8a6...,mc,9653f5baba69c9fb50bfb30a8571eb04dbceaae7c7f379...
34082,3a93817a680949d1559d42eb0e7d8184f885f6110a4728...,rpc,fa0a853d75a2227641a37861b97814dceca78ab7e0bba2...
22242,7b3b9cb2faed94c69ae18e8275ec186a4ffe6b2e258878...,rpc,7ac4b156dda86271b840fa6f4a5806566528142f6d5cc1...
33218,463d5a9c265fe101607a0cdf1e7e328409bbe093598c1f...,db,538971c676da692dcea34a7cdaffbfe77cfae1c6604949...
40965,23bdd392279c3f7f575cdcca6c022c7403272aea434e9e...,mc,1d78fdc13973c9e920734ee4c5ae7517ea0dc71840b12b...

In [12]:
test_df = remaining_df.drop(validation_df.index)  # drop the sampled rows to get the second DataFram
test_df

,um,rpctype,dm
1413,24601dd8b36f856eb0a4d759866f475bc62cf843ffe092...,rpc,cf5f15ad4585ff713e95993380824a1f0fc1d85792f8dd...
1742,6f83eed1237572824fa0807fb2414de831c989c6392cca...,rpc,6f83eed1237572824fa0807fb2414de831c989c6392cca...
1931,5d3c18d8b4f0aed80c31f3db4c3ef113a73106a41149cd...,mc,46a6d5047ff9337b34dbdf42c07843d60367ece052e92e...
2335,904df07378800893ad8ea3ed6411b954132d87d030ccea...,rpc,de93367b32ae1873de4c22a944ed1c95cc7d8e082d1ae0...
2564,5ba2be786dc249dc3b3cda596a4d121f55a1dcb75b399d...,mc,1ba37accfe145eb0ac812432bad415d1af09aa9cc7998c...
...,...,...,...
41374,4ea7a2cd9b19cab0716d540bec07fbe25ee7f513886858...,rpc,e310606888ea1e1a32da785c17ca8c8c37c95df5197b9b...
41376,ac06c2122ac45a80afb95e30fb2c0c73b96042efe4e6e3...,db,d975e4765706ce3b7a3f424ab5b848d206b5b8a7fa9bf0...
41378,5d887bdb9fd24cea365fb7ce018526df1d39b11630081b...,db,9d44d9b1700bbe79bc626669c2b036ed2d69c4fb59ba34...
41379,c20e26ec49d020ebe2b44aa6e3119993049eff078ff576...,db,8cce245e0d489e9ecf271400b101b92be1d371fe7895e5...
41383,a97b125d84a970b6461797b4106db49a6ba587416af9c5...,mq,13e763803f427787c427876463cf189a7f3c8e4182b0e0...

Transductive checks

In [13]:
train_entities = set(train_df['dm']) or set(train_df['um'])
valid_entities = set(validation_df['dm']) or set(validation_df['um'])
test_entities = set(test_df['dm']) or set(test_df['um'])

In [14]:
assert(valid_entities.issubset(train_entities))

In [15]:
assert(test_entities.issubset(train_entities))

In [16]:
train_relations = set(train_df['rpctype'])
valid_relations = set(validation_df['rpctype'])
test_relations = set(test_df['rpctype'])

In [17]:
assert(valid_relations.issubset(train_relations))

In [18]:
assert(test_relations.issubset(train_relations))

Check to see if there is test leakage

In [19]:
assert(0==len(pd.merge(train_df, validation_df)))

In [20]:
assert(0==len(pd.merge(train_df, test_df)))

In [21]:
assert(0==len(pd.merge(test_df, validation_df)))

In [22]:
def create_triplets(df):
    triplets = []
    for i in range(len(df)):
        head = df.iloc[i]['dm']
        tail = df.iloc[i]['um']
        rel = df.iloc[i]['rpctype']
        triplets.append([head,rel,tail])
    return triplets

In [23]:
import asposecells
import jpype
jpype.startJVM()

from asposecells.api import Workbook, FileFormatType

def create_tsv(triplets, file_name):


    # Create Workbook object.
    workbook = Workbook(FileFormatType.TSV)

    # Access the first worksheet of the workbook.
    worksheet = workbook.getWorksheets().get(0)

    # Get the desired cell(s) of the worksheet and input the value into the cell(s).


    i = 1
    for elem in triplets: 
        worksheet.getCells().get("A"+str(i)).putValue(elem[0])
        worksheet.getCells().get("B"+str(i)).putValue(elem[1])
        worksheet.getCells().get("C"+str(i)).putValue(elem[2])
        i+=1


    # Save the workbook as TSV file.
    workbook.save(file_name)


    file = open(file_name,'r')  
    lines = file.readlines()  
    file.close()
    file = open(file_name,'w')  
    lines = lines[:-1]
    file.writelines(lines)
    file.close()

In [24]:
datasets = [train_df, validation_df, test_df]
names = ["train", "validation","test"]

In [25]:
for elem in zip(datasets,names):
    create_tsv(create_triplets(elem[0]),f"MSCallGraph_{elem[1]}_transductive_sampled.tsv")
jpype.shutdownJVM()